openapi: "3.0.2"
info:
  title: users.yaml
  description: about users
  version:
servers:
  - url: 'http://localhost:8080'

paths:
  /users:
    get:
      summary: users
      responses:
        '200':
          description: successful response
        '500':
          $ref: '../responses/InternalErrorResponse.yaml'