openapi: "3.0.2"
info:
  title: api yaml
  description: test file
  version: 1.0.1
servers:
  - url: 'http://localhost:8080'

components:
  responses:
    InternalError:
      $ref: './responses/InternalErrorResponse.yaml'